import { DowntimeLog, DowntimeReason, DowntimeStatus } from "@/types";

export const mockDowntimeLogs: DowntimeLog[] = [
  {
    id: "dt-001",
    machineId: "machine-004",
    machineName: "AOI Inspector A4",
    reason: DowntimeReason.PLANNED_MAINTENANCE,
    description:
      "Scheduled monthly maintenance — camera calibration and lens cleaning",
    startTime: "2026-02-07T08:00:00Z",
    endTime: null,
    duration: null,
    reportedById: "user-002",
    reportedByName: "Napat Operator",
    resolvedById: null,
    status: DowntimeStatus.IN_PROGRESS,
    createdAt: "2026-02-07T08:00:00Z",
  },
  {
    id: "dt-002",
    machineId: "machine-007",
    machineName: "Palletizer B3",
    reason: DowntimeReason.BREAKDOWN,
    description:
      "Hydraulic arm malfunction — cylinder leaking, pressure drop detected",
    startTime: "2026-02-06T14:30:00Z",
    endTime: null,
    duration: null,
    reportedById: "user-003",
    reportedByName: "Kanya Operator",
    resolvedById: null,
    status: DowntimeStatus.OPEN,
    createdAt: "2026-02-06T14:30:00Z",
  },
  {
    id: "dt-003",
    machineId: "machine-012",
    machineName: "Function Tester C4",
    reason: DowntimeReason.BREAKDOWN,
    description: "Main controller board failure — unit not powering on",
    startTime: "2026-02-04T09:00:00Z",
    endTime: null,
    duration: null,
    reportedById: "user-002",
    reportedByName: "Napat Operator",
    resolvedById: null,
    status: DowntimeStatus.OPEN,
    createdAt: "2026-02-04T09:00:00Z",
  },
  {
    id: "dt-004",
    machineId: "machine-001",
    machineName: "SMT Placer A1",
    reason: DowntimeReason.CHANGEOVER,
    description:
      "Product changeover from Model X to Model Y — feeder reconfiguration",
    startTime: "2026-02-05T06:00:00Z",
    endTime: "2026-02-05T08:30:00Z",
    duration: 150,
    reportedById: "user-002",
    reportedByName: "Napat Operator",
    resolvedById: "user-002",
    resolvedByName: "Napat Operator",
    status: DowntimeStatus.RESOLVED,
    createdAt: "2026-02-05T06:00:00Z",
  },
  {
    id: "dt-005",
    machineId: "machine-006",
    machineName: "Box Former B2",
    reason: DowntimeReason.PLANNED_MAINTENANCE,
    description: "Weekly lubrication and belt tension adjustment",
    startTime: "2026-02-03T07:00:00Z",
    endTime: "2026-02-03T09:00:00Z",
    duration: 120,
    reportedById: "user-003",
    reportedByName: "Kanya Operator",
    resolvedById: "user-003",
    resolvedByName: "Kanya Operator",
    status: DowntimeStatus.RESOLVED,
    createdAt: "2026-02-03T07:00:00Z",
  },
  {
    id: "dt-006",
    machineId: "machine-009",
    machineName: "ICT Tester C1",
    reason: DowntimeReason.BREAKDOWN,
    description: "Test fixture pin damage — replaced 3 contact pins",
    startTime: "2026-02-01T11:00:00Z",
    endTime: "2026-02-01T15:30:00Z",
    duration: 270,
    reportedById: "user-002",
    reportedByName: "Napat Operator",
    resolvedById: "user-001",
    resolvedByName: "Somchai Admin",
    status: DowntimeStatus.RESOLVED,
    createdAt: "2026-02-01T11:00:00Z",
  },
  {
    id: "dt-007",
    machineId: "machine-002",
    machineName: "Reflow Oven A2",
    reason: DowntimeReason.PLANNED_MAINTENANCE,
    description: "Thermocouple calibration and heating element inspection",
    startTime: "2026-01-28T07:00:00Z",
    endTime: "2026-01-28T12:00:00Z",
    duration: 300,
    reportedById: "user-003",
    reportedByName: "Kanya Operator",
    resolvedById: "user-001",
    resolvedByName: "Somchai Admin",
    status: DowntimeStatus.RESOLVED,
    createdAt: "2026-01-28T07:00:00Z",
  },
  {
    id: "dt-008",
    machineId: "machine-005",
    machineName: "Labeler B1",
    reason: DowntimeReason.OTHER,
    description: "Label roll replacement and print head cleaning",
    startTime: "2026-01-30T13:00:00Z",
    endTime: "2026-01-30T13:45:00Z",
    duration: 45,
    reportedById: "user-003",
    reportedByName: "Kanya Operator",
    resolvedById: "user-003",
    resolvedByName: "Kanya Operator",
    status: DowntimeStatus.RESOLVED,
    createdAt: "2026-01-30T13:00:00Z",
  },
];
